# Generated by Django 5.1.6 on 2025-03-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0003_product_category_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='unit', max_length=50),
        ),
    ]
